#!/bin/sh
# triggers update on all the notebooks in container LLABSERVER
docker exec $LLABSERVER sh -c "echo $(date) >> /srv/notebook_update.log"
docker exec $LLABSERVER sh -c "/srv/update_dds_notebooks.sh >> /srv/notebook_update.log"
